import Head from 'next/head'
import Image from 'next/image'
import Some from "../public/some.jpg";
import Ariana from "../public/ariana.jpg"
import Vaan from "../public/vaana.jpg";
import Vaa from "../public/vaa.jpg";
import Ed from "../public/ed.jpeg";
import Sasha from "../public/sasha.jpg";
import George from "../public/george.jpeg";
import Akon from "../public/akon.jpeg";
import James from "../public/james.jpeg";


const someapi = [
  {
    pageNumber: 1,
    image: Ariana,
    artistName: "The weekend ft Ariana",
    songName: "Die for you (Remix)"
  },{
    pageNumber: 2,
    image: Vaan,
    artistName: "Ilayaraaja",
    songName: "Vaanam Mella"
  },{
    pageNumber: 3,
    image: Ed,
    artistName: "Ed Sheeran",
    songName: "Photograph"
  },{
    pageNumber: 4,
    image: Vaa,
    artistName: "Vaa",
    songName: "Vaa songs Remix"
  },
  {
    pageNumber: 5,
    image: Akon,
    artistName: "Akon",
    songName: "Convict Music Remix"
  },
  {
    pageNumber: 6,
    image: James,
    artistName: "James",
    songName: "Brave Heart"
  }
]

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section>
          <div className="bg-red-400 h-72 text-white font-bold pt-10">
            <h1 className="text-3xl text-center mt-10">TOP 10 MOST LISTENED SONGS</h1>
            <p className="text-center">In the past week</p>
          </div>
        </section>

        <section className="md:-mt-20">

          <div className="px-5 py-2 bg-white mb-10 md:shadow-2xl md:mx-40">
              <ul>
                {someapi.map((some)=>{
                  return(
                    <li className="flex justify-between mt-5" key={some.pageNumber}>
                      <div className="flex">
                      <span className="text-xl font-bold mr-3">{some.pageNumber}</span> 
                      <span> <Image src={some.image} alt='' width={100} /> </span>
                      <span className="text-xl font-bold ml-5">{some.songName} 
                        <p className="text-slate-600 text-sm">{some.artistName}</p>
                      </span>    
                      </div>
                    </li>
                  )
                })}
              </ul>
          </div>

        </section>
      </main>
    </>
  )
}
