import Head from 'next/head'
import Image from 'next/image'
import Some from "../public/some.jpg";
import Ariana from "../public/ariana.jpg"
import Vaan from "../public/vaana.jpg";
import Vaa from "../public/vaa.jpg";
import Ed from "../public/ed.jpeg";
import Sasha from "../public/sasha.jpg";
import George from "../public/george.jpeg";
import Akon from "../public/akon.jpeg";
import James from "../public/james.jpeg";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section>
          <div className="bg-red-400 h-72 text-white font-bold pt-10">
            <h1 className="text-3xl text-center mt-10">TOP 10 MOST LISTENED SONGS</h1>
            <p className="text-center">In the past week</p>
          </div>
        </section>

        <section className="md:-mt-20">

          <div className="px-5 py-2 bg-white mb-10 md:shadow-2xl md:mx-40">
            <ul>
              <li className="flex justify-between">
                <div className="flex">
                  <span className="text-xl font-bold mr-3">1</span> 
                  <span> <Image src={Ariana} alt='' width={100} /> </span>
                   <span className="text-xl font-bold ml-5">Die for you (remix) 
                    <p className="text-slate-600 text-sm">The weekend ft Ariana</p>
                   </span> 
                </div>
                <div>
                  <p>2,000,200</p>
                </div>
              </li>

              <li className="flex justify-between mt-5">
                <div className="flex">
                  <span className="text-xl font-bold mr-3">2</span> 
                  <span> <Image src={Vaan} alt='' width={100} /> </span>
                   <span className="text-2xl font-bold ml-5">Vaanam Mella 
                    <p className="text-slate-600 text-sm">Ilayaraaja</p>
                   </span> 
                </div>
                <div>
                  <p>2,000,200</p>
                </div>
              </li>

              <li className="flex justify-between mt-5">
                <div className="flex">
                  <span className="text-xl font-bold mr-3">3</span> 
                  <span> <Image src={Ed} alt='' width={100} /> </span>
                   <span className="text-2xl font-bold ml-5"> Photograph
                    <p className="text-slate-600 text-sm">Ed sheeran</p>
                   </span> 
                </div>
                <div>
                  <p>2,000,200</p>
                </div>
              </li>

              <li className="flex justify-between mt-5">
                <div className="flex">
                  <span className="text-xl font-bold mr-3">4</span> 
                  <span> <Image src={Sasha} alt='' width={100} /> </span>
                   <span className="text-xl font-bold ml-5">Is It Just Me? 
                    <p className="text-slate-600 text-sm">Sasha Alex Slaon</p>
                   </span> 
                </div>
                <div>
                  <p>2,000,200</p>
                </div>
              </li>

              <li className="flex justify-between mt-5">
                <div className="flex">
                  <span className="text-xl font-bold mr-3">5</span> 
                  <span> <Image src={Vaa} alt='' width={100} /> </span>
                   <span className="text-xl font-bold ml-5">Vaa Vaathi 
                    <p className="text-slate-600 text-sm">Dhanush</p>
                   </span> 
                </div>
                <div>
                  <p>2,000,200</p>
                </div>
              </li>

              <li className="flex justify-between mt-5">
                <div className="flex">
                  <span className="text-xl font-bold mr-3">6</span> 
                  <span> <Image src={George} alt='' width={100} /> </span>
                   <span className="text-xl font-bold ml-5">Carless Whisper 
                    <p className="text-slate-600 text-sm">George Michael</p>
                   </span> 
                </div>
                <div>
                  <p>2,000,200</p>
                </div>
              </li>

              <li className="flex justify-between mt-5">
                <div className="flex">
                  <span className="text-xl font-bold mr-3">7</span> 
                  <span> <Image src={Akon} alt='' width={100} /> </span>
                   <span className="text-xl font-bold ml-5">Over The Edge 
                    <p className="text-slate-600 text-sm">Akon</p>
                   </span> 
                </div>
                <div>
                  <p>2,000,200</p>
                </div>
              </li>

              <li className="flex justify-between mt-5">
                <div className="flex">
                  <span className="text-xl font-bold mr-3">8</span> 
                  <span> <Image src={James} alt='' width={100} /> </span>
                   <span className="text-xl font-bold ml-5">Gift Of A Thistle 
                    <p className="text-slate-600 text-sm">James Horner</p>
                   </span> 
                </div>
                <div>
                  <p>2,000,200</p>
                </div>
              </li>
            </ul>
          </div>


        </section>
      </main>
    </>
  )
}
